### ISSUE TITLE
[Glyph Vendor] Missing Glyphs

### ISSUE THREAD

**Issue by heyitsbench** [55Honey/Acore_ExchangeNpc#19]
[Glyph of Holy Shock](https://www.wowhead.com/wotlk/item=45746)
Requires level 40, inscription 430

[Glyph of Immolate](https://www.wowhead.com/wotlk/item=42464)
Requires level 15, inscription 385

**Comment by 55Honey** [comment]
https://github.com/55Honey/Acore_ExchangeNpc/blob/c028963265685f0335c42100e3b1651780faeaf4/database/world/ExchangeNpc_Up.sql#L21

That's where they go. Also requires a class condition below.
Thanks for the issue!
